/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#141b16",
        "surface": "#0a0f0b",
        "inverse-surface": "#f5fbf3",
        "inverse-on-surface": "#515751",
        "surface-container-highest": "#202821",
        "on-secondary-fixed-variant": "#006544",
        "surface-tint": "#bd9dff",
        "on-surface-variant": "#a7ada6",
        "error-dim": "#d73357",
        "tertiary-container": "#b8f9de",
        "surface-bright": "#252e27",
        "on-tertiary-container": "#22614d",
        "primary": "#bd9dff",
        "on-primary-fixed": "#000000",
        "surface-dim": "#0a0f0b",
        "on-secondary": "#005a3c",
        "secondary-dim": "#58e7ab",
        "secondary-container": "#006c49",
        "primary-fixed": "#b28cfe",
        "surface-container-low": "#0f1510",
        "secondary": "#69f6b8",
        "tertiary": "#e7fff3",
        "tertiary-fixed": "#b8f9de",
        "background": "#0a0f0b",
        "on-tertiary": "#2c6a55",
        "surface-container-lowest": "#000000",
        "on-primary": "#3b0a82",
        "on-surface": "#f8fef6",
        "on-tertiary-fixed-variant": "#2e6b57",
        "tertiary-fixed-dim": "#aaead0",
        "error": "#ff6e84",
        "outline-variant": "#434944",
        "outline": "#717771",
        "secondary-fixed-dim": "#58e7ab",
        "secondary-fixed": "#69f6b8",
        "surface-container-high": "#1a211c",
        "primary-fixed-dim": "#a47fef",
        "primary-dim": "#af89fb",
        "on-tertiary-fixed": "#074e3b",
        "on-primary-container": "#2e006c",
        "on-secondary-fixed": "#00452d",
        "on-error-container": "#ffb2b9",
        "tertiary-dim": "#9ddcc2",
        "surface-variant": "#202821",
        "on-secondary-container": "#e1ffec",
        "error-container": "#a70138",
        "on-background": "#f8fef6",
        "on-error": "#490013",
        "on-primary-fixed-variant": "#390480",
        "primary-container": "#b28cfe",
        "inverse-primary": "#6e49b6"
      },
    },
  },
  plugins: [],
}
