[theme]
primaryColor = "#FF7F50"
backgroundColor = "#0B1120"
secondaryBackgroundColor = "#151E2E"
textColor = "#FFFFFF"
font = "sans serif"

[server]
maxUploadSize = 200
[client]
showSidebarNavigation = false
